inherit_gem:
  rubocop-shopify: rubocop.yml

Style/ClassMethodsDefinitions:
  Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
