name: erb-lint

up:
  - homebrew:
    - openssl
    # - another_package
  - ruby: 2.5.3
  - bundler

commands:
  test:
    syntax:
      argument: file
      optional: args...
    run: bundle exec rspec "$@"
